// <auto-generated />
using GarageApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GarageApp.Migrations
{
    [DbContext(typeof(GarageDbContext))]
    [Migration("20260706122640_MoreDataAddedToTheDb")]
    partial class MoreDataAddedToTheDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GarageApp.Data.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GarageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GarageId");

                    b.ToTable("Cars", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GarageId = 1,
                            IsAvailable = true,
                            Make = "Audi",
                            Model = "A4",
                            Type = 0,
                            Year = 2016
                        },
                        new
                        {
                            Id = 2,
                            GarageId = 1,
                            IsAvailable = true,
                            Make = "BMW",
                            Model = "X5",
                            Type = 2,
                            Year = 2018
                        },
                        new
                        {
                            Id = 3,
                            GarageId = 1,
                            IsAvailable = true,
                            Make = "Mercedes-Benz",
                            Model = "C-Class",
                            Type = 0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 4,
                            GarageId = 1,
                            IsAvailable = false,
                            Make = "Toyota",
                            Model = "Corolla",
                            Type = 0,
                            Year = 2019
                        },
                        new
                        {
                            Id = 5,
                            GarageId = 1,
                            IsAvailable = true,
                            Make = "Ford",
                            Model = "Focus",
                            Type = 1,
                            Year = 2017
                        },
                        new
                        {
                            Id = 6,
                            GarageId = 2,
                            IsAvailable = false,
                            Make = "VW",
                            Model = "Golf",
                            Type = 1,
                            Year = 2014
                        },
                        new
                        {
                            Id = 7,
                            GarageId = 2,
                            IsAvailable = true,
                            Make = "Honda",
                            Model = "Civic",
                            Type = 0,
                            Year = 2021
                        },
                        new
                        {
                            Id = 8,
                            GarageId = 2,
                            IsAvailable = true,
                            Make = "Hyundai",
                            Model = "Tucson",
                            Type = 2,
                            Year = 2022
                        },
                        new
                        {
                            Id = 9,
                            GarageId = 2,
                            IsAvailable = true,
                            Make = "Nissan",
                            Model = "Qashqai",
                            Type = 2,
                            Year = 2020
                        },
                        new
                        {
                            Id = 10,
                            GarageId = 2,
                            IsAvailable = false,
                            Make = "Skoda",
                            Model = "Octavia",
                            Type = 0,
                            Year = 2018
                        });
                });

            modelBuilder.Entity("GarageApp.Data.Models.Garage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Garages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Sofia",
                            Name = "Central Garage"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Plovdiv",
                            Name = "Mountain Garage"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Varna",
                            Name = "East Garage"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Burgas",
                            Name = "West Garage"
                        },
                        new
                        {
                            Id = 5,
                            Location = "Ruse",
                            Name = "North Garage"
                        },
                        new
                        {
                            Id = 6,
                            Location = "Stara Zagora",
                            Name = "South Garage"
                        },
                        new
                        {
                            Id = 7,
                            Location = "Pleven",
                            Name = "Lakeside Garage"
                        },
                        new
                        {
                            Id = 8,
                            Location = "Veliko Tarnovo",
                            Name = "Valley Garage"
                        },
                        new
                        {
                            Id = 9,
                            Location = "Blagoevgrad",
                            Name = "Highway Garage"
                        },
                        new
                        {
                            Id = 10,
                            Location = "Dobrich",
                            Name = "Riverside Garage"
                        });
                });

            modelBuilder.Entity("GarageApp.Data.Models.Car", b =>
                {
                    b.HasOne("GarageApp.Data.Models.Garage", "Garage")
                        .WithMany("Cars")
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garage");
                });

            modelBuilder.Entity("GarageApp.Data.Models.Garage", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
