// <auto-generated />
using GarageApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GarageApp.Migrations
{
    [DbContext(typeof(GarageDbContext))]
    [Migration("20260706125533_MoreCarEntitiesAdded")]
    partial class MoreCarEntitiesAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GarageApp.Data.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GarageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GarageId");

                    b.ToTable("Cars", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GarageId = 1,
                            IsAvailable = true,
                            Make = "Audi",
                            Model = "A4",
                            Type = 0,
                            Year = 2016
                        },
                        new
                        {
                            Id = 2,
                            GarageId = 1,
                            IsAvailable = true,
                            Make = "BMW",
                            Model = "X5",
                            Type = 2,
                            Year = 2018
                        },
                        new
                        {
                            Id = 3,
                            GarageId = 1,
                            IsAvailable = false,
                            Make = "Toyota",
                            Model = "Corolla",
                            Type = 0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 4,
                            GarageId = 1,
                            IsAvailable = true,
                            Make = "Ford",
                            Model = "Focus",
                            Type = 1,
                            Year = 2017
                        },
                        new
                        {
                            Id = 5,
                            GarageId = 1,
                            IsAvailable = true,
                            Make = "Mercedes-Benz",
                            Model = "C-Class",
                            Type = 0,
                            Year = 2019
                        },
                        new
                        {
                            Id = 6,
                            GarageId = 2,
                            IsAvailable = true,
                            Make = "Honda",
                            Model = "Civic",
                            Type = 0,
                            Year = 2021
                        },
                        new
                        {
                            Id = 7,
                            GarageId = 2,
                            IsAvailable = false,
                            Make = "Volkswagen",
                            Model = "Golf",
                            Type = 1,
                            Year = 2018
                        },
                        new
                        {
                            Id = 8,
                            GarageId = 2,
                            IsAvailable = true,
                            Make = "Hyundai",
                            Model = "Tucson",
                            Type = 2,
                            Year = 2022
                        },
                        new
                        {
                            Id = 9,
                            GarageId = 2,
                            IsAvailable = true,
                            Make = "Kia",
                            Model = "Sportage",
                            Type = 2,
                            Year = 2021
                        },
                        new
                        {
                            Id = 10,
                            GarageId = 2,
                            IsAvailable = true,
                            Make = "Mazda",
                            Model = "Mazda3",
                            Type = 0,
                            Year = 2019
                        },
                        new
                        {
                            Id = 11,
                            GarageId = 3,
                            IsAvailable = true,
                            Make = "Nissan",
                            Model = "Altima",
                            Type = 0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 12,
                            GarageId = 3,
                            IsAvailable = true,
                            Make = "Subaru",
                            Model = "Outback",
                            Type = 2,
                            Year = 2019
                        },
                        new
                        {
                            Id = 13,
                            GarageId = 3,
                            IsAvailable = false,
                            Make = "Chevrolet",
                            Model = "Malibu",
                            Type = 0,
                            Year = 2018
                        },
                        new
                        {
                            Id = 14,
                            GarageId = 3,
                            IsAvailable = true,
                            Make = "Tesla",
                            Model = "Model 3",
                            Type = 0,
                            Year = 2022
                        },
                        new
                        {
                            Id = 15,
                            GarageId = 3,
                            IsAvailable = true,
                            Make = "Volvo",
                            Model = "XC60",
                            Type = 2,
                            Year = 2021
                        },
                        new
                        {
                            Id = 16,
                            GarageId = 4,
                            IsAvailable = true,
                            Make = "Audi",
                            Model = "Q5",
                            Type = 2,
                            Year = 2020
                        },
                        new
                        {
                            Id = 17,
                            GarageId = 4,
                            IsAvailable = true,
                            Make = "BMW",
                            Model = "3 Series",
                            Type = 0,
                            Year = 2019
                        },
                        new
                        {
                            Id = 18,
                            GarageId = 4,
                            IsAvailable = false,
                            Make = "Ford",
                            Model = "Escape",
                            Type = 2,
                            Year = 2021
                        },
                        new
                        {
                            Id = 19,
                            GarageId = 4,
                            IsAvailable = true,
                            Make = "Toyota",
                            Model = "RAV4",
                            Type = 2,
                            Year = 2022
                        },
                        new
                        {
                            Id = 20,
                            GarageId = 4,
                            IsAvailable = true,
                            Make = "Honda",
                            Model = "Accord",
                            Type = 0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 21,
                            GarageId = 5,
                            IsAvailable = true,
                            Make = "Mercedes-Benz",
                            Model = "GLA",
                            Type = 2,
                            Year = 2021
                        },
                        new
                        {
                            Id = 22,
                            GarageId = 5,
                            IsAvailable = false,
                            Make = "Volkswagen",
                            Model = "Passat",
                            Type = 0,
                            Year = 2019
                        },
                        new
                        {
                            Id = 23,
                            GarageId = 5,
                            IsAvailable = true,
                            Make = "Hyundai",
                            Model = "Elantra",
                            Type = 0,
                            Year = 2022
                        },
                        new
                        {
                            Id = 24,
                            GarageId = 5,
                            IsAvailable = true,
                            Make = "Kia",
                            Model = "Sorento",
                            Type = 2,
                            Year = 2020
                        },
                        new
                        {
                            Id = 25,
                            GarageId = 5,
                            IsAvailable = true,
                            Make = "Mazda",
                            Model = "CX-5",
                            Type = 2,
                            Year = 2021
                        },
                        new
                        {
                            Id = 26,
                            GarageId = 6,
                            IsAvailable = true,
                            Make = "Nissan",
                            Model = "Qashqai",
                            Type = 2,
                            Year = 2019
                        },
                        new
                        {
                            Id = 27,
                            GarageId = 6,
                            IsAvailable = true,
                            Make = "Subaru",
                            Model = "Forester",
                            Type = 2,
                            Year = 2020
                        },
                        new
                        {
                            Id = 28,
                            GarageId = 6,
                            IsAvailable = false,
                            Make = "Chevrolet",
                            Model = "Cruze",
                            Type = 0,
                            Year = 2018
                        },
                        new
                        {
                            Id = 29,
                            GarageId = 6,
                            IsAvailable = true,
                            Make = "Tesla",
                            Model = "Model Y",
                            Type = 2,
                            Year = 2023
                        },
                        new
                        {
                            Id = 30,
                            GarageId = 6,
                            IsAvailable = true,
                            Make = "Volvo",
                            Model = "S60",
                            Type = 0,
                            Year = 2021
                        },
                        new
                        {
                            Id = 31,
                            GarageId = 7,
                            IsAvailable = true,
                            Make = "Audi",
                            Model = "A6",
                            Type = 0,
                            Year = 2019
                        },
                        new
                        {
                            Id = 32,
                            GarageId = 7,
                            IsAvailable = true,
                            Make = "BMW",
                            Model = "X3",
                            Type = 2,
                            Year = 2022
                        },
                        new
                        {
                            Id = 33,
                            GarageId = 7,
                            IsAvailable = false,
                            Make = "Ford",
                            Model = "Fiesta",
                            Type = 1,
                            Year = 2017
                        },
                        new
                        {
                            Id = 34,
                            GarageId = 7,
                            IsAvailable = true,
                            Make = "Toyota",
                            Model = "Camry",
                            Type = 0,
                            Year = 2021
                        },
                        new
                        {
                            Id = 35,
                            GarageId = 7,
                            IsAvailable = true,
                            Make = "Honda",
                            Model = "CR-V",
                            Type = 2,
                            Year = 2022
                        },
                        new
                        {
                            Id = 36,
                            GarageId = 8,
                            IsAvailable = true,
                            Make = "Mercedes-Benz",
                            Model = "E-Class",
                            Type = 0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 37,
                            GarageId = 8,
                            IsAvailable = true,
                            Make = "Volkswagen",
                            Model = "Tiguan",
                            Type = 2,
                            Year = 2021
                        },
                        new
                        {
                            Id = 38,
                            GarageId = 8,
                            IsAvailable = false,
                            Make = "Hyundai",
                            Model = "i30",
                            Type = 1,
                            Year = 2019
                        },
                        new
                        {
                            Id = 39,
                            GarageId = 8,
                            IsAvailable = true,
                            Make = "Kia",
                            Model = "Rio",
                            Type = 1,
                            Year = 2020
                        },
                        new
                        {
                            Id = 40,
                            GarageId = 8,
                            IsAvailable = true,
                            Make = "Mazda",
                            Model = "6",
                            Type = 0,
                            Year = 2018
                        },
                        new
                        {
                            Id = 41,
                            GarageId = 9,
                            IsAvailable = true,
                            Make = "Nissan",
                            Model = "Juke",
                            Type = 2,
                            Year = 2021
                        },
                        new
                        {
                            Id = 42,
                            GarageId = 9,
                            IsAvailable = true,
                            Make = "Subaru",
                            Model = "Impreza",
                            Type = 0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 43,
                            GarageId = 9,
                            IsAvailable = false,
                            Make = "Chevrolet",
                            Model = "Equinox",
                            Type = 2,
                            Year = 2022
                        },
                        new
                        {
                            Id = 44,
                            GarageId = 9,
                            IsAvailable = true,
                            Make = "Tesla",
                            Model = "Model S",
                            Type = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 45,
                            GarageId = 9,
                            IsAvailable = true,
                            Make = "Volvo",
                            Model = "XC40",
                            Type = 2,
                            Year = 2021
                        },
                        new
                        {
                            Id = 46,
                            GarageId = 10,
                            IsAvailable = true,
                            Make = "Audi",
                            Model = "Q3",
                            Type = 2,
                            Year = 2022
                        },
                        new
                        {
                            Id = 47,
                            GarageId = 10,
                            IsAvailable = true,
                            Make = "BMW",
                            Model = "5 Series",
                            Type = 0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 48,
                            GarageId = 10,
                            IsAvailable = false,
                            Make = "Ford",
                            Model = "Kuga",
                            Type = 2,
                            Year = 2021
                        },
                        new
                        {
                            Id = 49,
                            GarageId = 10,
                            IsAvailable = true,
                            Make = "Toyota",
                            Model = "Yaris",
                            Type = 1,
                            Year = 2019
                        },
                        new
                        {
                            Id = 50,
                            GarageId = 10,
                            IsAvailable = true,
                            Make = "Honda",
                            Model = "Jazz",
                            Type = 1,
                            Year = 2018
                        });
                });

            modelBuilder.Entity("GarageApp.Data.Models.Garage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Garages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Sofia",
                            Name = "Central Garage"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Plovdiv",
                            Name = "Mountain Garage"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Varna",
                            Name = "East Garage"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Burgas",
                            Name = "West Garage"
                        },
                        new
                        {
                            Id = 5,
                            Location = "Ruse",
                            Name = "North Garage"
                        },
                        new
                        {
                            Id = 6,
                            Location = "Stara Zagora",
                            Name = "South Garage"
                        },
                        new
                        {
                            Id = 7,
                            Location = "Pleven",
                            Name = "Lakeside Garage"
                        },
                        new
                        {
                            Id = 8,
                            Location = "Veliko Tarnovo",
                            Name = "Valley Garage"
                        },
                        new
                        {
                            Id = 9,
                            Location = "Blagoevgrad",
                            Name = "Highway Garage"
                        },
                        new
                        {
                            Id = 10,
                            Location = "Dobrich",
                            Name = "Riverside Garage"
                        });
                });

            modelBuilder.Entity("GarageApp.Data.Models.Car", b =>
                {
                    b.HasOne("GarageApp.Data.Models.Garage", "Garage")
                        .WithMany("Cars")
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garage");
                });

            modelBuilder.Entity("GarageApp.Data.Models.Garage", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
